# -*- coding: utf-8 -*-
"""Pointcloud_preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMoXoxPHwPSyqngR8HXNxEhD1_-SjmyM
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install "pip<24.1"
!pip install -q cadquery-ocp trimesh tqdm networkx

import os, glob, json
from pathlib import Path

datapath = "/content/drive/MyDrive/MSCD_24_25/course_lectures/25Fall/Omni-CAD-subset"

txt_dir = os.path.join(datapath, "txt")
pc_dir  = os.path.join(datapath, "point_cloud")
step_dir = os.path.join(datapath, "step")

print("txt_dir:", txt_dir)
print("point_cloud_dir:", pc_dir)
print("step_dir:", step_dir)

print("\nFiles in txt:")
print(os.listdir(txt_dir))

print("\nSample files in point_cloud:")
pc_files = os.listdir(pc_dir)
print(pc_files[:10])

print("\nSample files in step:")
step_files = os.listdir(step_dir)
print(step_files[:10])

import json
import numpy as np
from pathlib import Path
from tqdm import tqdm

# ---- 必要的 OpenCascade imports（这几个必须有）----
from OCP.STEPControl import STEPControl_Reader
from OCP.BRepMesh import BRepMesh_IncrementalMesh
from OCP.TopExp import TopExp_Explorer
from OCP.TopAbs import TopAbs_FACE
from OCP.BRep import BRep_Tool
from OCP.TopLoc import TopLoc_Location


def step_to_dense_points_in_memory(step_path: Path, deflection: float = 0.5) -> np.ndarray:
    """
    用 OpenCascade 直接在内存里把 STEP 三角化，
    把所有三角网格的顶点收集成一个 dense point cloud.
    返回: (N, 3) 的 numpy 数组
    """
    step_reader = STEPControl_Reader()
    status = step_reader.ReadFile(str(step_path))
    if status != 1:
        raise RuntimeError(f"Failed to read STEP: {step_path}")

    # 把 STEP 转成 shape
    step_reader.TransferRoot()
    shape = step_reader.Shape()

    # 对 shape 做三角化（deflection 越小网格越密，但越慢）
    BRepMesh_IncrementalMesh(shape, deflection)

    # 遍历所有 FACE，取每个面的三角化节点
    exp = TopExp_Explorer(shape, TopAbs_FACE)
    all_pts = []

    while exp.More():
        face = exp.Current()          # ✅ 这里直接拿当前面，不用 topods_Face
        loc = TopLoc_Location()
        triangulation = BRep_Tool.Triangulation(face, loc)

        if triangulation is None:
            exp.Next()
            continue

        nodes = triangulation.Nodes()
        nb_nodes = triangulation.NbNodes()

        # OCCT 的 array 是 1-based index
        for i in range(1, nb_nodes + 1):
            pnt = nodes.Value(i)
            x, y, z = pnt.X(), pnt.Y(), pnt.Z()
            all_pts.append((x, y, z))

        exp.Next()

    if not all_pts:
        raise RuntimeError(f"No triangulation result for STEP: {step_path}")

    pts = np.array(all_pts, dtype=np.float64)
    return pts  # (N, 3)


def fps_downsample(points: np.ndarray, n_samples: int = 4096) -> np.ndarray:
    """
    简单的 Farthest Point Sampling (FPS)
    points: (N, 3)
    返回: (n_samples, 3)
    """
    N = points.shape[0]
    if N <= n_samples:
        return points

    selected = np.zeros(n_samples, dtype=int)
    # 随机起点
    selected[0] = np.random.randint(0, N)
    distances = np.full(N, np.inf)

    for i in range(1, n_samples):
        last = points[selected[i - 1]]
        dist = np.linalg.norm(points - last, axis=1)
        distances = np.minimum(distances, dist)
        selected[i] = np.argmax(distances)

    return points[selected]


def normalize_pc(pc: np.ndarray) -> np.ndarray:
    """
    平移到质心为 0，缩放到单位球
    """
    pc = pc - pc.mean(axis=0, keepdims=True)
    scale = np.max(np.linalg.norm(pc, axis=1))
    pc = pc / (scale + 1e-8)
    return pc.astype(np.float32)


def preprocess_pc_from_step_dir(
    step_root: str,
    out_root: str,
    n_samples: int = 4096,
    deflection: float = 0.5,
    limit_n: int | None = None,
):
    """
    直接从 step_root 下所有 .step / .stp 生成 point_cloud_small:

      STEP -> (in-memory triangulation) -> dense points -> FPS -> normalize -> .npz

    不再写 STL 文件，也不需要 trimesh.
    """
    step_root = Path(step_root)
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    step_files = list(step_root.rglob("*.step")) + list(step_root.rglob("*.stp"))
    print("found STEP files:", len(step_files))

    if limit_n is not None:
        step_files = step_files[:limit_n]
        print(f"⚠️ Only processing first {limit_n} files for testing")

    for step_path in tqdm(step_files):
        rel = step_path.relative_to(step_root).with_suffix("")  # e.g. 0002/00020000_00001
        out_path = out_root / rel.with_suffix(".npz")
        out_path.parent.mkdir(parents=True, exist_ok=True)

        if out_path.exists():
            continue

        try:
            dense_pts = step_to_dense_points_in_memory(step_path, deflection=deflection)
            pc = fps_downsample(dense_pts, n_samples=n_samples)
            pc = normalize_pc(pc)
            np.savez_compressed(out_path, points=pc)
        except Exception as e:
            print(f"[error] {step_path}: {e}")
            continue

    print("Done preprocessing from step_root only (in-memory triangulation)!")

import os
import numpy as np
from pathlib import Path
from tqdm import tqdm

# OpenCascade
from OCP.STEPControl import STEPControl_Reader
from OCP.BRepMesh import BRepMesh_IncrementalMesh
from OCP.StlAPI import StlAPI_Writer

import trimesh


def step_to_stl(step_path: Path,
                stl_path: Path,
                linear_deflection: float = 0.5,
                angular_deflection: float = 0.5,
                parallel: bool = True) -> None:
    """
    用 OpenCascade 把 STEP 转成 STL 网格文件（参考 CadQuery 的写法）
    """
    step_reader = STEPControl_Reader()
    status = step_reader.ReadFile(str(step_path))
    if status != 1:
        raise RuntimeError(f"Failed to read STEP: {step_path}")

    # 转成 shape
    step_reader.TransferRoot()
    shape = step_reader.Shape()

    # 先做三角化
    BRepMesh_IncrementalMesh(shape,
                             linear_deflection,
                             True,   # relative
                             angular_deflection,
                             parallel)

    # 确保目录存在
    stl_path.parent.mkdir(parents=True, exist_ok=True)

    # 写 STL（注意：这里用 ASCIIMode 属性，不用 SetASCIIMode）
    writer = StlAPI_Writer()
    writer.ASCIIMode = False   # binary STL，文件小一点
    ok = writer.Write(shape, str(stl_path))

    if (not ok) or (not stl_path.exists()):
        raise RuntimeError(f"Failed to write STL: {stl_path}")

def stl_to_dense_points(stl_path: Path, n_dense: int = 50000) -> np.ndarray:
    """
    用 trimesh 从 STL 表面均匀采样点
    """
    mesh = trimesh.load_mesh(str(stl_path), process=False)
    if mesh.is_empty:
        raise RuntimeError(f"Empty mesh for STL: {stl_path}")
    pts, _ = trimesh.sample.sample_surface(mesh, n_dense)
    return pts.astype(np.float64)


def fps_downsample(points: np.ndarray, n_samples: int = 4096) -> np.ndarray:
    """
    简单 Farthest Point Sampling (FPS)
    """
    N = points.shape[0]
    if N <= n_samples:
        return points

    selected = np.zeros(n_samples, dtype=int)
    selected[0] = np.random.randint(0, N)
    distances = np.full(N, np.inf)

    for i in range(1, n_samples):
        last = points[selected[i - 1]]
        dist = np.linalg.norm(points - last, axis=1)
        distances = np.minimum(distances, dist)
        selected[i] = np.argmax(distances)

    return points[selected]


def normalize_pc(pc: np.ndarray) -> np.ndarray:
    """
    平移到质心为 0，缩放到单位球
    """
    pc = pc - pc.mean(axis=0, keepdims=True)
    scale = np.max(np.linalg.norm(pc, axis=1))
    pc = pc / (scale + 1e-8)
    return pc.astype(np.float32)

def preprocess_pc_from_step_dir(
    step_root: str,
    out_root: str,
    n_dense: int = 50000,
    n_samples: int = 4096,
    tmp_stl_root: str | None = None,
    limit_n: int | None = None,
):
    """
    STEP 目录 → point_cloud_small 目录：

    STEP -> STL (临时) -> trimesh 采样表面点 -> FPS -> normalize -> .npz
    """
    step_root = Path(step_root)
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    tmp_stl_root_path = None
    if tmp_stl_root is not None:
        tmp_stl_root_path = Path(tmp_stl_root)
        tmp_stl_root_path.mkdir(parents=True, exist_ok=True)

    # 找所有 STEP
    step_files = list(step_root.rglob("*.step")) + list(step_root.rglob("*.stp"))
    print("found STEP files:", len(step_files))

    if limit_n is not None:
        step_files = step_files[:limit_n]
        print(f"⚠️ Only processing first {limit_n} files for testing")

    for step_path in tqdm(step_files):
        rel = step_path.relative_to(step_root).with_suffix("")  # 0002/00020000_00001
        out_path = out_root / rel.with_suffix(".npz")
        out_path.parent.mkdir(parents=True, exist_ok=True)

        if out_path.exists():
            continue

        # 决定 STL 存哪
        if tmp_stl_root_path is not None:
            stl_path = tmp_stl_root_path / rel.with_suffix(".stl")
            stl_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            stl_path = step_path.with_suffix(".stl")

        try:
            # STEP → STL
            step_to_stl(step_path, stl_path)

            # STL → dense pc
            dense_pts = stl_to_dense_points(stl_path, n_dense=n_dense)

            # FPS + normalize
            pc = fps_downsample(dense_pts, n_samples=n_samples)
            pc = normalize_pc(pc)

            # 保存
            out_path.parent.mkdir(parents=True, exist_ok=True)
            np.savez_compressed(out_path, points=pc)

        except Exception as e:
            print(f"[error] {step_path}: {e}")
            continue
        finally:
            # 如果是临时 STL，可以删掉节省空间
            if tmp_stl_root_path is not None and stl_path.exists():
                os.remove(stl_path)

    print("Done preprocessing from step_root (STEP → STL → point cloud)!")

from pathlib import Path

datapath = "/content/drive/MyDrive/MSCD_24_25/course_lectures/25Fall/Omni-CAD-subset"
step_root = f"{datapath}/step"
out_root  = f"{datapath}/point_cloud_small"
tmp_stl_root = "/content/tmp_stl"   # 临时文件放本地，避免 GDrive 慢 + 路径奇怪

print("step_root exists?", Path(step_root).exists())
print("out_root:", out_root)

# preprocess_pc_from_step_dir(
#     step_root=step_root,
#     out_root=out_root,
#     n_dense=20000,    # 测试用，先小一点
#     n_samples=2048,   # 点云大小
#     tmp_stl_root=tmp_stl_root,
#     limit_n=1,        # 👈 先处理 3 个 STEP
# )

import numpy as np
from pathlib import Path

out_root_path = Path(out_root)
small_files = list(out_root_path.rglob("*.npz"))
print("num small pcs:", len(small_files))
print("examples:", small_files[:3])

if small_files:
    data = np.load(small_files[0])
    print("keys:", data.files)
    pts = data["points"]
    print("points shape:", pts.shape)
    print("min:", pts.min(), "max:", pts.max())

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 (Colab 需要这个 import)

# 选一个点云文件
pc_path = small_files[0]   # 或者手动选某个路径
data = np.load(pc_path)
pts = data["points"]       # (N, 3)

print("points shape:", pts.shape)

# 如果点太多，可以再随机采样一下
N = pts.shape[0]
max_show = 2000
if N > max_show:
    idx = np.random.choice(N, max_show, replace=False)
    pts_vis = pts[idx]
else:
    pts_vis = pts

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection="3d")

x, y, z = pts_vis[:, 0], pts_vis[:, 1], pts_vis[:, 2]

# 用 z 作为颜色，看一下高度变化
sc = ax.scatter(x, y, z, s=3, alpha=0.8, c=z)

ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
ax.set_title(f"Point Cloud: {pc_path.name}")

plt.show()

!du -sh "/content/drive/MyDrive/MSCD_24_25/course_lectures/25Fall/Omni-CAD-subset/point_cloud_small"

N = 2048
bytes_per_pc = N * 3 * 4
print("bytes:", bytes_per_pc, "≈", bytes_per_pc / 1024, "KB")

from pathlib import Path

datapath = "/content/drive/MyDrive/MSCD_24_25/course_lectures/25Fall/Omni-CAD-subset"

# 把 step_root / out_root / tmp_stl_root 统一成 Path 对象
step_root = Path(datapath) / "step"
out_root  = Path(datapath) / "point_cloud_small"
tmp_stl_root = Path("/content/tmp_stl")

start_from = "0020"

subdirs = sorted([p for p in step_root.iterdir() if p.is_dir()])
print("subdirs:", [d.name for d in subdirs])

# 找到起始 index（例如从 0011 开始）
start_idx = 0
for i, d in enumerate(subdirs):
    if d.name >= start_from:
        start_idx = i
        break

for sub in subdirs[start_idx:]:
    print(f"\n=== Processing folder {sub.name} ===")
    sub_step_root = sub
    sub_out_root  = out_root / sub.name
    sub_tmp_stl   = tmp_stl_root / sub.name

    preprocess_pc_from_step_dir(
        step_root=str(sub_step_root),
        out_root=str(sub_out_root),
        n_dense=50000,
        n_samples=2048,
        tmp_stl_root=str(sub_tmp_stl),
        limit_n=None,
    )

import os
import datetime
import numpy as np
from pathlib import Path
from tqdm import tqdm

# 假设你已经定义了：
# step_to_stl(step_path, stl_path)
# stl_to_dense_points(stl_path, n_dense)
# fps_downsample(points, n_samples)
# normalize_pc(pc)


def preprocess_pc_from_step_dir(
    step_root: str,
    out_root: str,
    n_dense: int = 50000,
    n_samples: int = 4096,
    tmp_stl_root: str | None = None,
    limit_n: int | None = None,
    error_log_path: str | None = None,   # 现在是 "all logs"
):
    """
    STEP 目录 -> point cloud 目录：
    STEP -> STL -> trimesh 表面采样 -> FPS -> normalize -> .npz

    如果 error_log_path 不为 None，会把所有文件（成功 / 失败）的处理结果写到 log。
    """
    step_root = Path(step_root)
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    # 准备日志文件（记录所有结果）
    log_file = None
    if error_log_path is not None:
        log_file = Path(error_log_path)
        log_file.parent.mkdir(parents=True, exist_ok=True)
        if not log_file.exists():
            with log_file.open("w") as f:
                f.write("# timestamp | status | step_path | detail\n")

    # 临时 STL 目录
    tmp_stl_root_path = None
    if tmp_stl_root is not None:
        tmp_stl_root_path = Path(tmp_stl_root)
        tmp_stl_root_path.mkdir(parents=True, exist_ok=True)

    # 收集所有 STEP
    step_files = list(step_root.rglob("*.step")) + list(step_root.rglob("*.stp"))
    print("found STEP files:", len(step_files))

    if limit_n is not None:
        step_files = step_files[:limit_n]
        print(f"⚠️ Only processing first {limit_n} files for testing")

    for step_path in tqdm(step_files):
        rel = step_path.relative_to(step_root).with_suffix("")  # 0002/00020000_00001
        out_path = out_root / rel.with_suffix(".npz")
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # 决定 STL 路径
        if tmp_stl_root_path is not None:
            stl_path = tmp_stl_root_path / rel.with_suffix(".stl")
            stl_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            stl_path = step_path.with_suffix(".stl")

        ts = datetime.datetime.now().isoformat(timespec="seconds")

        # 如果点云已经存在，也记录到 log 里（状态：SKIP）
        if out_path.exists():
            msg = f"[{ts}] SKIP | {step_path} | npz exists: {out_path}"
            print(msg)
            if log_file is not None:
                with log_file.open("a") as f:
                    f.write(msg + "\n")
            continue

        try:
            # STEP -> STL
            step_to_stl(step_path, stl_path)

            # STL -> dense points
            dense_pts = stl_to_dense_points(stl_path, n_dense=n_dense)

            # FPS + normalize
            pc = fps_downsample(dense_pts, n_samples=n_samples)
            pc = normalize_pc(pc)

            # 存 .npz
            np.savez_compressed(out_path, points=pc)

            # 成功也写 log（状态：OK）
            msg = f"[{ts}] OK   | {step_path} | saved: {out_path}"
            print(msg)
            if log_file is not None:
                with log_file.open("a") as f:
                    f.write(msg + "\n")

        except Exception as e:
            # 失败写 log（状态：ERROR）
            msg = f"[{ts}] ERROR| {step_path} | {repr(e)}"
            print(msg)
            if log_file is not None:
                with log_file.open("a") as f:
                    f.write(msg + "\n")
            continue

        finally:
            # 清理临时 STL
            if tmp_stl_root_path is not None and stl_path.exists():
                try:
                    os.remove(stl_path)
                except OSError:
                    pass

    print("Done preprocessing from step_root (STEP → STL → point cloud)!")

from pathlib import Path

datapath = "/content/drive/MyDrive/MSCD_24_25/course_lectures/25Fall/Omni-CAD-subset"
log_path = Path(datapath) / "logs" / "step2pc_all.txt"   # 👈 现在记录全部结果

# 把 step_root / out_root / tmp_stl_root 统一成 Path 对象
step_root = Path(datapath) / "step"
out_root  = Path(datapath) / "point_cloud_small"
tmp_stl_root = Path("/content/tmp_stl")

start_from = "0030"

subdirs = sorted([p for p in step_root.iterdir() if p.is_dir()])
print("subdirs:", [d.name for d in subdirs])

# 找到起始 index
start_idx = 0
for i, d in enumerate(subdirs):
    if d.name >= start_from:
        start_idx = i
        break

for sub in subdirs[start_idx:]:
    print(f"\n=== Processing folder {sub.name} ===")
    sub_step_root = sub
    sub_out_root  = out_root / sub.name
    sub_tmp_stl   = tmp_stl_root / sub.name

    preprocess_pc_from_step_dir(
        step_root=str(sub_step_root),
        out_root=str(sub_out_root),
        n_dense=50000,
        n_samples=2048,
        tmp_stl_root=str(sub_tmp_stl),
        limit_n=None,
        error_log_path=str(log_path),   # 👈 现在是“全量 log”
    )