# Stage 3
CUDA_VISIBLE_DEVICES=4 python scripts/train_curriculum.py \
    --use_wandb \
    --output_dir ./CAD-MLLM-checkpoints \
    --omnicad_json_root ./data/Omni-CAD-subset-complete/json \
    --omnicad_txt_path ./data/Omni-CAD-subset-complete/txt \
    --omnicad_img_root ./data/Omni-CAD-subset-complete/img \
    --omnicad_pc_root ./data/Omni-CAD-subset-complete/pointcloud \
    --llm_model_name "Qwen/Qwen3-8B" \
    --resume_from_ckpt "./CAD-MLLM-checkpoints/stage3_all/checkpoint-epoch0-step100-20251128_220651" \
    --start_from_stage 3 \
    --stage1_epochs 0 \
    --stage2_epochs 0 \
    --stage3_epochs 10 \
    --stage3_lr 2e-5 \
    --max_seq_length 1024 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lora_r 32 \
    --lora_alpha 64 \
    --warmup_steps 50 \
    --logging_steps 1000 \
    --save_steps 50 \
    --device cuda \
    --dtype bfloat16 \
    --wandb_project "CAD-MLLM-stage_3" \
    --wandb_run_name "latent_pc" \
    --wandb_entity "yizhuod-cmu" \
    --seed 30